In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    'Name': ['Aman', 'Riya', 'Rahul', 'Priya'],
    'Age': [20, 19, 21, 20],
    'City': ['Delhi', 'Agra', 'Mathura', 'Noida']
}

In [ ]:
student_df = pd.DataFrame(data)

In [ ]:
student_df

    Name  Age     City
0   Aman   20    Delhi
1   Riya   19     Agra
2  Rahul   21  Mathura
3  Priya   20    Noida

In [ ]:
student_df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [ ]:
student_df['Name']

0     Aman
1     Riya
2    Rahul
3    Priya
Name: Name, dtype: object

In [ ]:
student_df['City']

0      Delhi
1       Agra
2    Mathura
3      Noida
Name: City, dtype: object

In [ ]:
new_df = student_df[['Name', 'City']]
new_df

    Name     City
0   Aman    Delhi
1   Riya     Agra
2  Rahul  Mathura
3  Priya    Noida

In [ ]:
data = {
    'Book': ['Python Basics', 'DBMS', 'Data Science'],
    'Author': ['Amit', 'Rahul', 'Neha'],
    'Price': [350, 400, 500]
}

In [ ]:
book_df = pd.DataFrame(data)

In [ ]:
book_df

            Book Author  Price
0  Python Basics   Amit    350
1           DBMS  Rahul    400
2   Data Science   Neha    500

In [ ]:
book_df['Publisher'] = 'ABC Publications'

In [ ]:
book_df

            Book Author  Price         Publisher
0  Python Basics   Amit    350  ABC Publications
1           DBMS  Rahul    400  ABC Publications
2   Data Science   Neha    500  ABC Publications

In [ ]:
df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rahul', 'Priya', 'Karan']
})

In [ ]:
df['SerialNo'] = np.arange(5)

In [ ]:
df

    Name  SerialNo
0   Aman         0
1   Riya         1
2  Rahul         2
3  Priya         3
4  Karan         4

In [ ]:
df.drop('SerialNo', axis=1, inplace=True)

In [ ]:
df

    Name
0   Aman
1   Riya
2  Rahul
3  Priya
4  Karan

In [ ]:
movie_df = pd.DataFrame({
    'Movie': ['3 Idiots', 'Dangal', 'PK'],
    'Year': [2009, 2016, 2014],
    'Rating': [8.4, 8.3, 8.1]
})

In [ ]:
movie_df

      Movie  Year  Rating
0  3 Idiots  2009     8.4
1    Dangal  2016     8.3
2        PK  2014     8.1

In [ ]:
new_movie_df = movie_df.reindex(
    columns=['Movie', 'Rating', 'Director']
)

In [ ]:
new_movie_df

      Movie  Rating  Director
0  3 Idiots     8.4       NaN
1    Dangal     8.3       NaN
2        PK     8.1       NaN

In [ ]:
cities = pd.Series(
    ['Delhi', 'Mumbai'],
    index=[0, 3]
)

In [ ]:
cities

0     Delhi
3    Mumbai
dtype: object

In [ ]:
branch_df = pd.DataFrame({
    'Student': ['Aman', 'Riya', 'Rahul', 'Priya']
})

In [ ]:
branch_df['Branch'] = cities

In [ ]:
branch_df

  Student  Branch
0    Aman   Delhi
1    Riya     NaN
2   Rahul     NaN
3   Priya  Mumbai

In [ ]:
copied_df = pd.read_clipboard()

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error