In [ ]:
import numpy as np
from pandas import Series,DataFrame
import pandas as pd

In [ ]:
sales = Series([120,150,180,210])

In [ ]:
marks = Series([72, 81, 69, 90])

In [ ]:
marks.values

array([72, 81, 69, 90])

In [ ]:
marks

0    72
1    81
2    69
3    90
dtype: int64

In [ ]:
temp = Series([28,31,30,29], index = ['mon','tue','wed','thu'])

In [ ]:
temp

mon    28
tue    31
wed    30
thu    29
dtype: int64

In [ ]:
population = Series([35, 42, 31],index = ['Delhi','Mumbai','Jaipur'])

In [ ]:
population['Jaipur']

np.int64(31)

In [ ]:
score = Series([35, 68, 44, 79, 52])

In [ ]:
score[score > 50]

1    68
3    79
4    52
dtype: int64

In [ ]:
subjects = Series([76, 83, 91], index=['Physics','Chemistry','Maths'])

In [ ]:
subjects.isnull()

Physics      False
Chemistry    False
Maths        False
dtype: bool

In [ ]:
print("Q7:", 'Chemistry' in subjects.index)

Q7: True

In [ ]:
print( subjects.to_dict())

{'Physics': 76, 'Chemistry': 83, 'Maths': 91}

In [ ]:
prices = {'Pen': 10, 'Notebook': 55, 'Bag': 700}

In [ ]:
price_series = Series(prices)

In [ ]:
price_series

Pen          10
Notebook     55
Bag         700
dtype: int64

In [ ]:
print("The dictionary keys become the Series index.")

The dictionary keys become the Series index.

In [ ]:
data = {'A': 10, 'B': 20, 'C': 30}

In [ ]:
s = Series(data, index=['A', 'B', 'C', 'D'])

In [ ]:
s[s.isnull()].index[0]

'D'

In [ ]:
s.isnull()

A    False
B    False
C    False
D     True
dtype: bool

In [ ]:
s.notnull()

A     True
B     True
C     True
D    False
dtype: bool

In [ ]:
sales = Series([100, 200, 300])
sales.name = 'Monthly Sales'

In [ ]:
sales

0    100
1    200
2    300
Name: Monthly Sales, dtype: int64

In [ ]:
sales.index.name = 'Month'

In [ ]:
sales.index.name

'Month'

In [ ]:
s = Series([18, 45, 27, 61], index=['P', 'Q', 'R', 'S'])

In [ ]:
s[s > 30]

Q    45
S    61
dtype: int64

In [ ]:
s = Series([500, 600, 700], index=['East', 'West', 'North'])

In [ ]:
'West' in s

True

In [ ]:
500 in s

False

In [ ]:
city_data = {'Delhi': 80, 'Pune': 65, 'Kochi': 70}

In [ ]:
s = Series(city_data, index=['Delhi', 'Kochi', 'Pune', 'Chennai'])

In [ ]:
s

Delhi      80.0
Kochi      70.0
Pune       65.0
Chennai     NaN
dtype: float64

In [ ]:
s = Series(
    {'W': 5, 'X': 10, 'Y': 15},
    index=['W', 'X', 'Y', 'Z'])

In [ ]:
s

W     5.0
X    10.0
Y    15.0
Z     NaN
dtype: float64

In [ ]:
pd.notnull(s)

W     True
X     True
Y     True
Z    False
dtype: bool

In [ ]:
s1 = Series([10, 20, 30], index=['A', 'B', 'C'])
s2 = Series([1, 2, 3], index=['C', 'A', 'B'])

In [ ]:
s1 + s2

A    12
B    23
C    31
dtype: int64

In [ ]:
s1 = Series({'A': 12, 'B': 18})
s2 = Series({'B': 5, 'C': 9})

In [ ]:
s1+s2

A     NaN
B    23.0
C     NaN
dtype: float64

In [ ]:
stock = Series([25, 40, 18], index=['Item1', 'Item2', 'Item3'])

In [ ]:
stock.to_dict()

{'Item1': 25, 'Item2': 40, 'Item3': 18}

In [ ]:
Series(stock_dict)

NameError: name 'stock_dict' is not defined

In [ ]:
marks = {'Maths': 88,'Science': 74,'English': 69,'History': 81
}

In [ ]:
s = Series(marks, index=['History', 'English', 'Science', 'Maths'])

In [ ]:
s[s > 70]

History    81
Science    74
Maths      88
dtype: int64

In [ ]:
rev = Series([50000, 75000, 60000], index=['Delhi', 'Pune', 'Kochi'])

In [ ]:
rev.name = 'Revenue'

In [ ]:
rev

Delhi    50000
Pune     75000
Kochi    60000
Name: Revenue, dtype: int64

In [ ]:
s = Series({'W': 5, 'X': 10, 'Y': 15},
           index=['W', 'X', 'Y', 'Z'])

In [ ]:
pd.isnull(s)

Category
W    False
X    False
Y    False
Z     True
Name: Observations, dtype: bool

In [ ]:
pd.notnull(s)

Category
W     True
X     True
Y     True
Z    False
Name: Observations, dtype: bool

In [ ]:
s1 = Series([10, 20, 30], index=['A', 'B', 'C'])
s2 = Series([1, 2, 3], index=['C', 'A', 'B'])

In [ ]:
s1 + s2

A     NaN
B    23.0
C     NaN
dtype: float64

In [ ]:
s1 = Series({'A': 12, 'B': 18})
s2 = Series({'B': 5, 'C': 9})

In [ ]:
s1 + s2

A     NaN
B    23.0
C     NaN
dtype: float64

In [ ]:
stock = Series([25, 40, 18],
               index=['Item1', 'Item2', 'Item3'])

In [ ]:
stock_dict = stock.to_dict()
stock2 = Series(stock_dict)

In [ ]:
stock_dict

{'Item1': 25, 'Item2': 40, 'Item3': 18}

In [ ]:
stock2

Item1    25
Item2    40
Item3    18
dtype: int64

In [ ]:
marks = {
    'Maths': 88,
    'Science': 74,
    'English': 69,
    'History': 81
}

In [ ]:
s = Series(marks, index=['History', 'English', 'Science', 'Maths'])

In [ ]:
s

History    81
English    69
Science    74
Maths      88
dtype: int64

In [ ]:
s[s > 70]

History    81
Science    74
Maths      88
dtype: int64

In [ ]:
north = Series({'Jan': 40, 'Feb': 55, 'Mar': 60})
south = Series({'Feb': 20, 'Mar': 25, 'Apr': 30})

In [ ]:
total = north + south

In [ ]:
total

Apr     NaN
Feb    75.0
Jan     NaN
Mar    85.0
dtype: float64

In [ ]:
d = {'Red': 12, 'Blue': 18, 'Green': 24}
labels = ['Green', 'Red', 'Yellow', 'Blue']

In [ ]:
result = Series(d, index=labels)

In [ ]:
result
pd.isnull(result)

Green     False
Red       False
Yellow     True
Blue      False
dtype: bool

In [ ]:
s = Series([90, 75, 82],
           index=['Ravi', 'Aman', 'Neha'])

In [ ]:
d = s.to_dict()
s2 = Series(d)

In [ ]:
d
s2

Ravi    90
Aman    75
Neha    82
dtype: int64

In [ ]:
sales = Series(
    [650, 420, 800, 350],
    index=['Laptop', 'Mouse', 'Keyboard', 'Monitor']
)

In [ ]:
sales.values

array([650, 420, 800, 350])

In [ ]:
sales.index

Index(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], dtype='object')

In [ ]:
sales['Laptop']

np.int64(650)

In [ ]:
data = {'A': 15, 'B': 35, 'C': 25}
s = Series(data, index=['C', 'A', 'D', 'B'])

In [ ]:
s

C    25.0
A    15.0
D     NaN
B    35.0
dtype: float64

In [ ]:
s[s > 20]

C    25.0
B    35.0
dtype: float64

In [ ]:
pd.notnull(s)

C     True
A     True
D    False
B     True
dtype: bool

In [ ]:
s.name

In [ ]:
s.index.name

In [ ]:
s.name = 'Observations'
s.index.name = 'Category'

In [ ]:
s

C    25.0
A    15.0
D     NaN
B    35.0
dtype: float64

In [ ]:
s[s > 20]

C    25.0
B    35.0
dtype: float64

In [ ]:
pd.notnull(s)

C     True
A     True
D    False
B     True
dtype: bool

In [ ]:
s.name

In [ ]:
s.index.name